---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: true
configure_apps: false
personal_tasks: true
jamf_tasks: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - Maps
 - Photos
 - FaceTime
 - Contacts
 - Freeform
 - TV
 - News
 - Keynote
 - Numbers
 - Pages
 - 'App Store'

dockitems_persist:
 - name: "Obsidian"
   path: "/Applications/Obsidian.app/"
   pos: 4
 - name: "Visual Studio Code"
   path: "/Applications/Visual Studio Code.app/"
   pos: 5
 - name: "Slack"
   path: "/Applications/Slack.app/"
   pos: 6
 - name: "Suspicious Package"
   path: "/Applications/Suspicious Package.app/"
   pos: 7

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/camdenwebster/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/config/dotfiles
dotfiles_files:
  - .osx
  - .gitconfig
  - .zshrc
  - .gitignore_global
  - .zprofile
  - .obsidian
  - .vscode
  - .nextcloud

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bitwarden-cli
  - carthage
  - git
  - git-lfs
  - gh
  - openssl
  - ssh-copy-id
  - tart

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - figma
  - github
  - google-chrome
  - home-assistant
  - microsoft-remote-desktop
  - mist
  - nextcloud
  - obsidian
  - proxyman
  - raycast
  - reader
  - setapp
  - sf-symbols
  - shottr
  - slack
  - sqlpro-for-sqlite
  - suspicious-package
  - tailscale
  - utm
  - visual-studio-code
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - {id: 497799835, name: "Xcode"}
  - {id: 1476964367, name: "InYourFace"}
  - {id: 302584613, name: "Kindle"}
  - {id: 417375580, name: "BetterSnapTool"}
  - {id: 1352778147, name: "Bitwarden"}
  - {id: 1291898086, name: "Toggl Track"}

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
