---
# Copy app settings into their necessary directories after installation is complete

- name: VSCode settings exists
  stat:
    path: ~/Library/Application\ Support/Code/User/settings.json
  register: vscode_settings

- name: Zed settings exists
  stat:
    path: ~/.config/zed/settings.json
  register: zed_settings

- name: Copy VSCode settings
  copy:
    src: ~/.vscode/settings.json
    dest: ~/Library/Application\ Support/Code/User/settings.json
  changed_when: false
  when: not vscode_settings.stat.exists

- name: Copy Zed settings
  copy:
    src: ~/.zed/settings.json
    dest: ~/.config/zed/settings.json
  changed_when: false
  when: not zed_settings.stat.exists
