#!/bin/bash

# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Add user-level Python to PATH
export PATH="$HOME/Library/Python/3.9/bin:/opt/homebrew/bin:$PATH"

# Create config directory in the home folder
if [ -d ~/config/ ]; then
  cd ~/config/
else
  echo "Creating dir at ~/config"
  mkdir ~/config
  cd ~/config/

fi

# Clone or pull mac-dev-playbook repo into the config directory (using HTTPS)
if [ -d ~/config/mac-dev-playbook/.git ]; then
  cd ~/config/mac-dev-playbook/
  git pull
else
  git clone https://github.com/camdenwebster/mac-dev-playbook.git
fi

# Install Ansible
pip3 install ansible

# Download mac-dev-playbook requirements
cd ~/config/mac-dev-playbook/
ansible-galaxy install -r requirements.yml

# Run Ansible playbook
ansible-playbook main.yml --ask-become-pass
